plugins {
    id 'com.android.application'
}

android {
    namespace 'gr.playnest.app'
    compileSdk 35

    defaultConfig {
        applicationId "gr.playnest.app"
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName "1.5"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
}
